import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
const [board,bb]=await Promise.all([fetch('main.json').then(r=>r.json()),fetch('../breadboard/layout.json').then(r=>r.json())]);
const $=id=>document.getElementById(id);$('title').textContent=bb.adc+' • staged recorder';
const scene=new THREE.Scene();scene.background=new THREE.Color('#111b2a');const camera=new THREE.PerspectiveCamera(42,1,.1,3000);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));$('canvas').appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x52617f,3));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(100,200,100);scene.add(light);
let group=new THREE.Group(),targets=[],pcbModel=null;scene.add(group);new GLTFLoader().load('main.glb',g=>{pcbModel=g.scene;if($('mode').value==='pcb')build()},undefined,()=>{$('status').textContent='PCB model could not load; check export.'});
const colors=n=>n==='GND'?0x68758d:/3V|5V|VBAT/.test(n)?0xef6868:/RAW|AIN|RC|BUF|VMID/.test(n)?0xfacb5b:/DRDY|BUSY|INT|CONVST/.test(n)?0xba96ff:0x63d6ce;
function text(s,x,y,z,size=4){let c=document.createElement('canvas');c.width=768;c.height=80;let ctx=c.getContext('2d');ctx.fillStyle='#e7f0ff';ctx.font='32px sans-serif';ctx.fillText(s,8,48);let t=new THREE.CanvasTexture(c),m=new THREE.Sprite(new THREE.SpriteMaterial({map:t,depthTest:false}));m.position.set(x,y,z);m.scale.set(size*9.6,size,1);group.add(m);return m}
function box(x,y,z,w,h,d,col,data){let o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:col}));o.position.set(x,y,z);group.add(o);if(data){o.userData=data;targets.push(o)}return o}
function wire(a,b,net){let c=new THREE.QuadraticBezierCurve3(new THREE.Vector3(...a),new THREE.Vector3((a[0]+b[0])/2,Math.max(a[1],b[1])+5,(a[2]+b[2])/2),new THREE.Vector3(...b));let o=new THREE.Mesh(new THREE.TubeGeometry(c,12,.3,5,false),new THREE.MeshBasicMaterial({color:colors(net)}));o.userData={name:net,net,role:'Connection endpoints: '+a.join(', ')+' → '+b.join(', ')};targets.push(o);group.add(o);return o}
function select(data){$('detail').textContent=JSON.stringify(data,null,2);for(const o of targets){if(o.material){o.material.opacity=!data.net||o.userData.net===data.net?1:.18;o.material.transparent=true}}requestAnimationFrame(()=>renderer.render(scene,camera))}
function build(){scene.remove(group);group=new THREE.Group();scene.add(group);targets=[];const stage=+$('stage').value;const spread=+$('explode').value;const pcb=$('mode').value==='pcb';$('stageLabel').textContent='Stage '+stage;const sel=$('parts');sel.innerHTML='<option value="">Select a component / connection</option>';
 if(pcb){if(pcbModel){let model=pcbModel.clone(true);model.scale.setScalar(1000);model.position.set(-37.5,0,-25);group.add(model);model.traverse(o=>{let part=board.parts.find(p=>p.ref===o.name);if(part){o.position.y+=spread/1000;o.traverse(m=>{if(m.isMesh){m.material=m.material.clone();m.userData={name:part.ref+' '+part.value,role:part.section,terminals:part.pads};targets.push(m)}})}});}
 for(const t of board.tracks){if(t.via)continue;let geometry=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(t.a[0]-37.5,1.9,t.a[1]-25),new THREE.Vector3(t.b[0]-37.5,1.9,t.b[1]-25)]);let line=new THREE.Line(geometry,new THREE.LineBasicMaterial({color:colors(t.net),transparent:true,opacity:0.1}));line.userData={name:'Net '+t.net+' ('+t.layer+')',net:t.net,role:'Actual routed PCB track',endpoints:[t.a,t.b]};group.add(line);targets.push(line)}
 if(stage>=10){for(let ch=0;ch<+$('channels').value;ch++){const x=100,z=-30+ch*22;box(x,2,z,28,4,16,0x8135ad,{name:'MyoWare EMG'+(ch+1),role:'Approximate sensor envelope; no electrodes/person connected during bench tests'});const connector=board.parts.find(p=>p.ref==='J'+(5+ch));for(const pad of connector.pads.filter(p=>['1','2','3'].includes(p.pin)))wire([pad.x-37.5,3,pad.y-25],[x-14,3,z+(+pad.pin-2)*3],pad.net)}}
 text('Actual KiCad board geometry • all circuitry populated',0,20,-32,4);if(stage>=6){box(-55,0,0,16,3,22,0x257d8c,{name:'Foot IMU module',role:'Approximate ready-made ICM-42688-P board'});box(55,0,0,16,3,22,0x257d8c,{name:'Shank IMU module',role:'Approximate ready-made ICM-42688-P board'});wire([-55,2,0],[6.5,2,-21.3],'FOOT_SPI');wire([55,2,0],[23.5,2,-21.3],'SHANK_SPI')}
 }else{
 let modules=[['Power / 3.3 V / 3.0 V / midpoint',1,-90,-62],['ESP32-S3-N8R8 controller',2,-15,-62],[bb.module,3,65,-62],['Foot + shank IMU modules',6,65,70],['microSD interface',7,-15,70],['Wi-Fi to laptop',8,-90,70],['Protected battery',9,-90,-95]];
 for(const [name,s,x,z]of modules)if(stage>=s){box(x,1,z,58,4,22,0x246e74,{name,role:'Functional block. Module dimensions and terminal coordinates NOT verified.'});text(name,x,8,z,3);if(s>1)wire([x,3,z],[-90,3,-62],s===9?'VBAT':'3V3D')}
 if(stage>=3)wire([-15,3,-62],[65,3,-62],'ADC_SERIAL • verify module header before wiring');
 for(let ch=-1;ch<4;ch++){if(ch>=0&&(stage<4||(ch>0&&stage<5)))continue;let id='BB'+(ch+1),x=ch===-1?-165:-100+ch*(65+spread/2),z=0;box(x,0,z,52,3,90,0xcad2d9,{name:id,role:'Analog breadboard EMG'+(ch+1)+'; a–e and f–j strips separated; no power-rail assumptions'});let pos=h=>{let col='abcdefghij'.indexOf(h[0]);return [x+(col-4.5)*4+(col<5?-2:2),3,(+h.slice(1)-17)*2.54]};for(let row=1;row<=33;row++)for(let col of 'abcdefghij'){let a=pos(col+row);box(...a,.65,.2,.65,0x566575)}text(ch===-1?'Midpoint BB0':'EMG'+(ch+1)+(ch>=+$('channels').value?' · disabled':''),x,9,-48,3.5);
 for(const p of bb.components.filter(p=>p.board===id)){let holes=Object.values(p.terminals),a=pos(holes[0]),b=pos(holes.at(-1));box((a[0]+b[0])/2,6+spread/8,(a[2]+b[2])/2,Math.max(2,Math.abs(a[0]-b[0])+2),3,Math.max(2,Math.abs(a[2]-b[2])+2),p.ref.startsWith('U')?0x22252d:p.ref.startsWith('R')?0xcaac79:0x438caf,{name:p.ref+' '+p.value,terminals:p.terminals,board:id});}
 const terminals=new Map();for(const c of bb.connections.filter(c=>c.board===id)){let a=pos(c.from_hole),b;if(c.to_hole.includes(':')){if(!terminals.has(c.to_hole)){let ix=terminals.size;terminals.set(c.to_hole,[x-23+(ix%5)*11,5,48+Math.floor(ix/5)*10]);}b=terminals.get(c.to_hole)}else b=pos(c.to_hole);wire(a,b,c.net).userData={name:id+' '+c.net,net:c.net,from:c.from_hole,to:c.to_hole,role:'Breadboard wire; external endpoints are functional labels, NOT a module pin map.'}}
 if(stage>=10&&ch>=0&&ch<+$('channels').value){box(x,2,86,30,4,18,0x8135ad,{name:'MyoWare EMG'+(ch+1),role:'Approximate module; RAW output to matching analog channel'});const raw=terminals.get('TERMINAL:RAW'+ch);if(raw)wire([x,4,77],raw,'RAW'+ch)}
 }
 }
 const listed=new Set();targets.forEach((o,i)=>{const label=o.userData.net?'Net '+o.userData.net:o.userData.name;if(listed.has(label))return;listed.add(label);let opt=document.createElement('option');opt.value=i;opt.textContent=label;sel.append(opt)});requestAnimationFrame(()=>renderer.render(scene,camera));$('status').textContent='Engineering prototype • no hardware test results • external module header positions unverified';}
$('parts').onchange=e=>{if(e.target.value!=='')select(targets[+e.target.value].userData)};for(let id of ['mode','stage','explode','channels'])$(id).oninput=()=>{build();if(id==='mode'||id==='stage')$('reset').click()};$('reset').onclick=()=>{camera.position.set(...($('mode').value==='pcb'?(+$('stage').value>=10?[145,150,200]:[65,85,95]):[30,260,290]));controls.target.set(0,0,0);controls.update()};$('reset').click();
renderer.domElement.onclick=e=>{let r=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);let hit=ray.intersectObjects(targets)[0];if(hit)select(hit.object.userData)};
function resize(){let r=$('canvas').getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();requestAnimationFrame(()=>renderer.render(scene,camera))}window.onresize=resize;resize();build();controls.addEventListener("change",()=>requestAnimationFrame(()=>renderer.render(scene,camera)));window.afoViewer={get targets(){return targets.length},get mode(){return $('mode').value}};
