const $=id=>document.getElementById(id);
const names=['Power & midpoint','Controller','ADC & timing','First EMG input','Second EMG input','Motion sensors','SD recording','Wi-Fi reception','Battery operation','MyoWare integration'];
const rail=$('stageRail'),stage=$('stage');
if(rail&&stage){names.forEach((name,i)=>{const b=document.createElement('button');b.type='button';b.innerHTML=`<span class="num">${String(i+1).padStart(2,'0')}</span><span>${name}</span>`;b.onclick=()=>{stage.value=String(i+1);stage.dispatchEvent(new Event('change',{bubbles:true}))};rail.appendChild(b)});const sync=(updateUrl=false)=>{const n=Number(stage.value)||Number(new URLSearchParams(location.search).get("stage"))||1;[...rail.children].forEach((b,i)=>{b.classList.toggle('active',i+1===n);if(i+1===n)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')});if($('stageBadge'))$('stageBadge').textContent=`STAGE ${String(n).padStart(2,'0')} / 10`;if($('stageName'))$('stageName').textContent=names[n-1];if($('guideLink'))$('guideLink').href=`build.html?stage=${n}`;if(updateUrl===true){const u=new URL(location);u.searchParams.set('stage',n);history.replaceState(null,'',u)}};stage.addEventListener('change',()=>sync(true));document.addEventListener('stage-render',()=>sync(true));new MutationObserver(()=>sync()).observe(stage,{childList:true});sync();}
const tabs=[...document.querySelectorAll('[data-pane]')];function tab(name){tabs.forEach(b=>{const on=b.dataset.pane===name;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on));document.querySelector(`[data-content="${b.dataset.pane}"]`).hidden=!on})}tabs.forEach(b=>b.onclick=()=>tab(b.dataset.pane));
if($('wireSearch')){const filter=()=>{const q=$('wireSearch').value.toLowerCase();let count=0;[...$('wireSelect').options].forEach((o,i)=>{o.hidden=i>0&&!o.text.toLowerCase().includes(q);if(i>0&&!o.hidden)count++});$('searchCount').textContent=count+' matching connections'};$('wireSearch').oninput=filter;new MutationObserver(filter).observe($('wireSelect'),{childList:true});}
if($('focusCanvas'))$('focusCanvas').onclick=()=>{const on=document.body.classList.toggle('focus-mode');$('focusCanvas').textContent=on?'Exit focus':'Focus canvas';$('focusCanvas').setAttribute('aria-pressed',String(on));window.dispatchEvent(new Event('resize'));$('fit').click()};
document.addEventListener('keydown',e=>{if(e.metaKey||e.ctrlKey||e.altKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='f'&&$('fit'))$('fit').click();if(e.key==='t'&&$('top'))$('top').click();if(e.key==='/'&&$('wireSearch')){e.preventDefault();tab('wires');$('wireSearch').focus()}if(e.key==='Escape'&&document.body.classList.contains('focus-mode'))$('focusCanvas').click()});
if($('wireInfo'))new MutationObserver(()=>tab('wires')).observe($('wireInfo'),{childList:true});
if($('moduleInfo'))new MutationObserver(()=>tab('modules')).observe($('moduleInfo'),{childList:true});
// Feedback is textual as well as visual, and never represents a measured pass.

tabs.forEach((b,i)=>{b.tabIndex=b.classList.contains('active')?0:-1;b.id='tab-'+b.dataset.pane;b.setAttribute('aria-controls','pane-'+b.dataset.pane);const pane=document.querySelector(`[data-content="${b.dataset.pane}"]`);pane.id='pane-'+b.dataset.pane;pane.setAttribute('role','tabpanel');pane.setAttribute('aria-labelledby',b.id);b.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%tabs.length;if(e.key==='ArrowLeft')n=(i+tabs.length-1)%tabs.length;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;if(n!==undefined){e.preventDefault();tab(tabs[n].dataset.pane);tabs.forEach((x,j)=>x.tabIndex=j===n?0:-1);tabs[n].focus()}});b.addEventListener('click',()=>tabs.forEach(x=>x.tabIndex=x===b?0:-1))});
