const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const [a,w,g]=await Promise.all(['../breadboard/assembly.json','../breadboard/system-wiring.json','guide.json'].map(u=>fetch(u,{cache:'no-store'}).then(r=>r.json())));
const key='recorder-build-guide-'+a.variant;let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch{};let stage=Math.max(1,Math.min(10,Number(new URLSearchParams(location.search).get('stage'))||saved.stage||1));
$('name').textContent=a.title;$('owner').textContent=g.signature;
for(let i=1;i<=10;i++)$('stage').add(new Option(`${i}. ${g.stages[i-1].title}`,i));
function save(){saved.stage=stage;localStorage.setItem(key,JSON.stringify(saved))}
function render(){const s=g.stages[stage-1],v=saved[stage]||{};$('stage').value=stage;$('progress').textContent=`Stage ${stage} of 10`;$('heading').textContent=s.title;$('purpose').textContent=s.purpose;$('power').textContent=stage<9?'Test power: current-limited lab supply. Battery stays disconnected.': 'Battery power: disconnect BOTH lab-supply leads before connecting the protected battery.';
$('add').innerHTML=s.add.map(x=>`<li>${esc(x)}</li>`).join('');$('test').innerHTML=s.tests.map(x=>`<li>${esc(x)}</li>`).join('');$('trouble').textContent=s.troubleshoot;$('acceptance').textContent=s.acceptance;
const parts=a.boards.flatMap(b=>b.steps.filter(x=>x.kind==='component'&&(x.stage||b.stage)===stage).map(x=>({b,...x})));
$('parts').innerHTML=parts.length?parts.map(x=>`<tr><td>${esc(x.b.id)}</td><td>${esc(x.title)}</td><td>${esc(x.holes.join(', '))}</td><td>${esc(x.orientation||'See component markings and the hole table.')}</td></tr>`).join(''):'<tr><td colspan="4">No new breadboard components in this stage. Add only the modules listed above.</td></tr>';
const leads=w.connections.filter(x=>x.stage===stage);const jumpers=a.boards.filter(b=>b.stage===stage).flatMap(b=>b.steps.filter(x=>x.kind==='jumper').map(x=>({id:x.id,net:x.net,from:b.id+':'+x.from,to:b.id+':'+x.to,note:'Internal breadboard jumper'})));
const harness=(a.physical_harness||[]);const rows=[...leads.map(x=>({id:x.id,net:x.net,from:x.a.module+':'+x.a.terminal,to:x.b.module+':'+x.b.terminal,note:x.note})),...jumpers,...harness.filter(x=>Math.max(...[x.a,x.b].map(e=>a.boards.find(b=>b.id===e.board)?.stage||1))===stage).map(x=>({id:x.id,net:x.net,from:x.a.board+":"+x.a.hole,to:x.b.board+":"+x.b.hole,note:"Inter-board harness. Install with power off."}))];
$('wires').innerHTML=rows.map(x=>`<tr><td><input type="checkbox" aria-label="Assembled ${esc(x.id)}" data-wire="${esc(x.id)}" ${saved.wires?.[x.id]?'checked':''}></td><td>${esc(x.id)}<br><b>${esc(x.net)}</b></td><td>${esc(x.from)}</td><td>${esc(x.to)}</td><td>${esc(x.note)}</td></tr>`).join('')||'<tr><td colspan="5">No new permanent wiring. Follow the test instructions.</td></tr>';
$('wires').querySelectorAll('input').forEach(x=>x.onchange=()=>{saved.wires??={};saved.wires[x.dataset.wire]=x.checked;save()});
$('viewer').href=`index.html?v=15&stage=${stage}`;$('full').href='index.html?v=15&stage=10';$('outcome').value=v.outcome||'not-tested';$('notes').value=v.notes||'';$('previous').disabled=stage===1;$('next').disabled=stage===10;
$('gate').textContent=v.outcome==='pass'?'You recorded PASS. Keep the supporting readings and evidence. This is not independent certification.':v.outcome==='fail'?'You recorded FAIL. Correct the fault and repeat this stage before adding hardware.':'Not tested. You may browse later stages, but do not advance the physical build until this stage passes.';save();document.dispatchEvent(new Event('stage-render'));}
async function init(){a.physical_harness=await fetch('../breadboard/physical-harness.json').then(r=>r.json());render()}
$('stage').onchange=()=>{stage=Number($('stage').value);render()};$('previous').onclick=()=>{stage--;render()};$('next').onclick=()=>{stage++;render()};$('record').onclick=()=>{saved[stage]={outcome:$('outcome').value,notes:$('notes').value,recorded_at:new Date().toISOString(),source:'user-entered'};save();render();$('saved').textContent='Saved in this browser. Export a copy to keep with your test evidence.'};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({variant:a.variant,signature:g.signature,exported_at:new Date().toISOString(),independently_verified:false,...saved},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=a.variant+'-build-results.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};$('print').onclick=()=>print();await init();
